### ISSUE TITLE
Piranha-micro jar returns no main manifest attribute

### ISSUE THREAD

**Issue by otaviojava** [piranhacloud/piranha#701] opened 2020-05-05 18:20 UTC
Given a project wth this pom.xml

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>sh.platform.template</groupId>
    <artifactId>piranha</artifactId>
    <packaging>war</packaging>
    <version>1.0.0-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <platform.sh.version>2.2.3</platform.sh.version>
    </properties>

    <dependencies>

        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <version>4.0.3</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>sh.platform</groupId>
            <artifactId>config</artifactId>
            <version>${platform.sh.version}</version>
        </dependency>
        <dependency>
            <groupId>cloud.piranha</groupId>
            <artifactId>piranha-micro</artifactId>
            <version>20.4.0</version>
        </dependency>
    </dependencies>
    <build>
        <finalName>piranha</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.2.3</version>
                <configuration>
                    <failOnMissingWebXml>false</failOnMissingWebXml>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.1.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>cloud.piranha</groupId>
                                    <artifactId>piranha-micro</artifactId>
                                    <version>20.4.0</version>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

When I execute:

```
mvn clean package
java -jar target/dependency/piranha-micro-20.4.0.jar target/piranha.war 
```
It returns: ```no main manifest attribute, in target/dependency/piranha-micro-20.4.0.jar```

**Comment by manorrock** [comment] 2020-05-05 18:26
Currently the -all JAR has everything you need. It is available from http://repo1.maven.org/maven2/cloud/piranha/piranha-micro/20.4.0/piranha-micro-20.4.0-all.jar

**Comment by otaviojava** [comment] 2020-05-06 07:39
@manorrock 
Hey, I've tested with this WAR and it does not work even with this jar file.
https://github.com/platformsh-templates/piranha/tree/update

Could you check it, please?

**Comment by manorrock** [comment] 2020-05-07 12:49
@otaviojava If you go straight to http://localhost:8080/index.jsp or http://localhost:8080/hello in your example application it will work. I have filed issue #709 to add the missing functionality around welcome-file. Thanks for trying out our in progress project!

**Comment by manorrock** [comment] 2020-05-09 13:38
@otaviojava Issue #709 has now been fixed and it will be part of the upcoming May release. Thank you for trying out Piranha!

**Comment by otaviojava** [comment] 2020-05-11 09:42
it does not work.
What Java version are you using?
It returns 404.
I'm using Java 11

**Comment by manorrock** [comment] 2020-05-14 21:56
Can you try with the 20.5.0 version?

**Comment by otaviojava** [comment] 2020-05-14 22:03
```
java -jar piranha-micro-20.5.0-all.jar target/piranha.war 
java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:138)
	at cloud.piranha.webapp.impl.DefaultWebApplicationResponse.writeStatusLine(DefaultWebApplicationResponse.java:946)
	at cloud.piranha.webapp.impl.DefaultWebApplicationResponse.writeOut(DefaultWebApplicationResponse.java:927)
	at cloud.piranha.webapp.impl.DefaultWebApplicationResponse.flushBuffer(DefaultWebApplicationResponse.java:292)
	at cloud.piranha.webapp.impl.DefaultWebApplication.service(DefaultWebApplication.java:1538)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer.service(DefaultWebApplicationServer.java:271)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer.process(DefaultWebApplicationServer.java:234)
	at cloud.piranha.http.impl.DefaultHttpServerProcessingThread.run(DefaultHttpServerProcessingThread.java:83)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:138)
	at cloud.piranha.webapp.impl.DefaultWebApplicationResponse.writeStatusLine(DefaultWebApplicationResponse.java:946)
	at cloud.piranha.webapp.impl.DefaultWebApplicationResponse.writeOut(DefaultWebApplicationResponse.java:927)
	at cloud.piranha.webapp.impl.DefaultWebApplicationResponse.flushBuffer(DefaultWebApplicationResponse.java:292)
	at cloud.piranha.webapp.impl.DefaultWebApplication.service(DefaultWebApplication.java:1538)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer.service(DefaultWebApplicationServer.java:271)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer.process(DefaultWebApplicationServer.java:234)
	at cloud.piranha.http.impl.DefaultHttpServerProcessingThread.run(DefaultHttpServerProcessingThread.java:83)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:138)
	at cloud.piranha.webapp.impl.DefaultWebApplicationResponse.writeStatusLine(DefaultWebApplicationResponse.java:946)
	at cloud.piranha.webapp.impl.DefaultWebApplicationResponse.writeOut(DefaultWebApplicationResponse.java:927)
	at cloud.piranha.webapp.impl.DefaultWebApplicationResponse.flushBuffer(DefaultWebApplicationResponse.java:292)
	at cloud.piranha.webapp.impl.DefaultWebApplication.service(DefaultWebApplication.java:1538)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer.service(DefaultWebApplicationServer.java:271)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer.process(DefaultWebApplicationServer.java:234)
	at cloud.piranha.http.impl.DefaultHttpServerProcessingThread.run(DefaultHttpServerProcessingThread.java:83)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by manorrock** [comment] 2020-05-15 01:31
Is there a location where I can get the WAR file you are using?

**Comment by otaviojava** [comment] 2020-05-15 07:58
Link: 
https://www.dropbox.com/s/19ore0g2jb53qug/piranha.war?dl=0

**Comment by manorrock** [comment] 2020-05-15 22:49
OK I have checked http://localhost:8080/hello and that works. Investigating why index.jsp does not work.

**Comment by otaviojava** [comment] 2020-05-16 10:43
@manorrock both URL do not work for me.
What is your Java version?


When I go to: http://localhost:8080/hello


It returns:

```
java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:138)
	at cloud.piranha.webapp.impl.DefaultWebApplicationResponse.writeStatusLine(DefaultWebApplicationResponse.java:946)
	at cloud.piranha.webapp.impl.DefaultWebApplicationResponse.writeOut(DefaultWebApplicationResponse.java:927)
	at cloud.piranha.webapp.impl.DefaultWebApplicationResponse.flushBuffer(DefaultWebApplicationResponse.java:292)
	at cloud.piranha.webapp.impl.DefaultWebApplication.service(DefaultWebApplication.java:1538)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer.service(DefaultWebApplicationServer.java:271)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer.process(DefaultWebApplicationServer.java:234)
	at cloud.piranha.http.impl.DefaultHttpServerProcessingThread.run(DefaultHttpServerProcessingThread.java:83)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:138)
	at cloud.piranha.webapp.impl.DefaultWebApplicationResponse.writeStatusLine(DefaultWebApplicationResponse.java:946)
	at cloud.piranha.webapp.impl.DefaultWebApplicationResponse.writeOut(DefaultWebApplicationResponse.java:927)
	at cloud.piranha.webapp.impl.DefaultWebApplicationResponse.flushBuffer(DefaultWebApplicationResponse.java:292)
	at cloud.piranha.webapp.impl.DefaultWebApplication.service(DefaultWebApplication.java:1538)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer.service(DefaultWebApplicationServer.java:271)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer.process(DefaultWebApplicationServer.java:234)
	at cloud.piranha.http.impl.DefaultHttpServerProcessingThread.run(DefaultHttpServerProcessingThread.java:83)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by manorrock** [comment] 2020-05-16 16:21
@arjantijms Can you have a look?

**Comment by manorrock** [comment] 2020-06-04 12:52
@otaviojava Can you try with the latest SNAPSHOT version?

**Comment by otaviojava** [comment] 2020-06-05 11:55
The same error:

```
java -jar piranha-micro-20.5.0-20200420.034219-1-all.jar piranha.war 
jun 05, 2020 8:55:11 AM cloud.piranha.http.impl.DefaultHttpServer start
INFO: Starting HTTP server on port 8.080
jun 05, 2020 8:55:11 AM cloud.piranha.http.impl.DefaultHttpServer start
INFO: Started HTTP server on port 8.080

``

**Comment by Thihup** [comment] 2020-06-05 12:00
Can you try cloning and building the project? (_mvn clean install_ at top directory should do the work)
The result will be at `micro/target/piranha-micro-20.6.0-SNAPSHOT-all.jar`

**Comment by arjantijms** [comment] 2020-06-05 18:47
@otaviojava It seems to work though:

```
java -jar ./target/piranha-micro-20.6.0-SNAPSHOT-all.jar --war ~/Downloads/piranha.war 


SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Jun 05, 2020 8:36:35 PM cloud.piranha.micro.MicroInnerDeployer start
INFO: Starting web application e6c4c1ed-17c8-430c-b5a3-15d4b1d547e9.jar on Piranha Micro20.6.0-SNAPSHOT
Jun 05, 2020 8:36:37 PM org.jboss.weld.environment.servlet.Listener contextInitialized
INFO: WELD-ENV-001007: Initialize Weld using ServletContextListener
Jun 05, 2020 8:36:37 PM org.jboss.weld.bootstrap.WeldStartup <clinit>
INFO: WELD-000900: 3.1.4 (Final)
Jun 05, 2020 8:36:37 PM org.jboss.weld.environment.deployment.discovery.DiscoveryStrategyFactory create
INFO: WELD-ENV-000020: Using jandex for bean discovery
Jun 05, 2020 8:36:37 PM org.jboss.weld.bootstrap.WeldStartup startContainer
INFO: WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
Jun 05, 2020 8:36:37 PM org.glassfish.soteria.servlet.SamRegistrationInstaller onStartup
INFO: Initializing Soteria null for context ''
```

<img width="374" alt="Running war" src="https://user-images.githubusercontent.com/3037006/83911695-fb247b00-a76c-11ea-98e1-5679bc85ae75.png">

The important thing is to use **20.6.0** and not **20.5.0**.

**Comment by otaviojava** [comment] 2020-06-05 18:49
ahhh ok, let me try the 20.6.0  version.

**Comment by arjantijms** [comment] 2020-06-05 18:50
> ahhh ok, let me try the 20.6.0 version.

thx :)

**Comment by otaviojava** [comment] 2020-06-05 20:27
It returns this error: 

```
java -jar piranha-micro-20.6.0-SNAPSHOT-all.jar piranha.war 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
jun 05, 2020 5:25:54 PM cloud.piranha.micro.MicroInnerDeployer start
INFO: Starting web application 0df04851-bb67-41b9-bda4-c600be0fcb60.war on Piranha Micro20.6.0-SNAPSHOT
jun 05, 2020 5:25:54 PM org.jboss.weld.environment.servlet.Listener contextInitialized
INFO: WELD-ENV-001007: Initialize Weld using ServletContextListener
jun 05, 2020 5:25:54 PM org.jboss.weld.bootstrap.WeldStartup <clinit>
INFO: WELD-000900: 3.1.4 (Final)
jun 05, 2020 5:25:55 PM org.jboss.weld.environment.deployment.discovery.DiscoveryStrategyFactory create
INFO: WELD-ENV-000020: Using jandex for bean discovery
jun 05, 2020 5:25:55 PM org.jboss.weld.environment.servlet.WeldServletLifecycle initialize
WARN: WELD-ENV-000028: Weld initialization skipped - no bean archive found
jun 05, 2020 5:25:55 PM cloud.piranha.webapp.impl.DefaultWebApplication initializeInitializers
WARNING: Initializer cloud.piranha.security.jakarta.JakartaSecurityAllInitializer failing onStartup
java.lang.IllegalStateException: Singleton not set for cloud.piranha.webapp.impl.DefaultWebApplication@19b30c92 => []
	at org.jboss.weld.bootstrap.api.helpers.RegistrySingletonProvider$RegistrySingleton.get(RegistrySingletonProvider.java:28)
	at org.jboss.weld.Container.instance(Container.java:65)
	at org.jboss.weld.module.web.servlet.WeldInitialListener.contextInitialized(WeldInitialListener.java:81)
	at org.jboss.weld.servlet.api.helpers.ForwardingServletListener.contextInitialized(ForwardingServletListener.java:34)
	at org.jboss.weld.environment.servlet.Listener.contextInitialized(Listener.java:121)
	at cloud.piranha.cdi.weld.WeldInitializer.onStartup(WeldInitializer.java:64)
	at cloud.piranha.security.jakarta.JakartaSecurityAllInitializer.onStartup(JakartaSecurityAllInitializer.java:101)
	at cloud.piranha.webapp.impl.DefaultWebApplication.initializeInitializers(DefaultWebApplication.java:1369)
	at cloud.piranha.webapp.impl.DefaultWebApplication.initialize(DefaultWebApplication.java:1320)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer.lambda$initialize$0(DefaultWebApplicationServer.java:214)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:976)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer.initialize(DefaultWebApplicationServer.java:210)
	at cloud.piranha.micro.MicroInnerDeployer.start(MicroInnerDeployer.java:184)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at cloud.piranha.micro.MicroOuterDeployer.deploy(MicroOuterDeployer.java:162)
	at cloud.piranha.micro.MicroPiranha.run(MicroPiranha.java:131)
	at cloud.piranha.micro.MicroPiranha.main(MicroPiranha.java:73)

jun 05, 2020 5:25:55 PM cloud.piranha.webapp.impl.DefaultWebApplication initializeFinish
WARNING: An error occurred initializing webapplication at 
java.lang.RuntimeException: Unable to start servicing
	at cloud.piranha.webapp.impl.DefaultWebApplication.verifyState(DefaultWebApplication.java:2004)
	at cloud.piranha.webapp.impl.DefaultWebApplication.start(DefaultWebApplication.java:1899)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer.lambda$start$1(DefaultWebApplicationServer.java:317)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:976)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer.start(DefaultWebApplicationServer.java:313)
	at cloud.piranha.micro.MicroInnerDeployer.start(MicroInnerDeployer.java:185)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at cloud.piranha.micro.MicroOuterDeployer.deploy(MicroOuterDeployer.java:162)
	at cloud.piranha.micro.MicroPiranha.run(MicroPiranha.java:131)
	at cloud.piranha.micro.MicroPiranha.main(MicroPiranha.java:73)
Exception in thread "main" java.lang.IllegalStateException: 
	at cloud.piranha.micro.MicroOuterDeployer.deploy(MicroOuterDeployer.java:171)
	at cloud.piranha.micro.MicroPiranha.run(MicroPiranha.java:131)
	at cloud.piranha.micro.MicroPiranha.main(MicroPiranha.java:73)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at cloud.piranha.micro.MicroOuterDeployer.deploy(MicroOuterDeployer.java:162)
	... 2 more
Caused by: java.lang.RuntimeException: Unable to start servicing
	at cloud.piranha.webapp.impl.DefaultWebApplication.verifyState(DefaultWebApplication.java:2004)
	at cloud.piranha.webapp.impl.DefaultWebApplication.start(DefaultWebApplication.java:1899)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer.lambda$start$1(DefaultWebApplicationServer.java:317)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:976)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer.start(DefaultWebApplicationServer.java:313)
	at cloud.piranha.micro.MicroInnerDeployer.start(MicroInnerDeployer.java:185)

```
I'm using Java 11. 

- https://www.dropbox.com/s/2mbbsslnk5q4a4z/piranha-micro-20.6.0-SNAPSHOT-all.jar?dl=0
- https://www.dropbox.com/s/19ore0g2jb53qug/piranha.war?dl=0

**Comment by arjantijms** [comment] 2020-06-05 20:39
Hi, it's very important not to omit the `--war` argument:

```
java -jar piranha-micro-20.6.0-SNAPSHOT-all.jar --war piranha.war 
```

That argument is **absolutely** crucial in running a war at this moment. Since the project is still in its early stages we haven't yet implemented all the polishing to warn about missing arguments or to try to infer what was intended etc.

**Comment by otaviojava** [comment] 2020-06-05 21:04
It works, thank you :)

**Comment by arjantijms** [comment] 2020-06-05 21:05
Yeah! :) Thanks for reporting back!

**Closed** 2020-06-05 21:49 UTC
Labels: question
