### ISSUE TITLE
Accessing via HTTPS protocol and HTTP port produces `java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds`

### ISSUE THREAD

**Issue by ParadoxV5** [piranhacloud/piranha#2619] opened 2022-06-26 20:05 UTC
### To Reproduce
1. Download Piranha Micro
2. `$ java -jar path/to/piranha.jar`
    * This issue occurs to me whether I include `--war-file something.war` or not.
3. Open a web browser and head to https://localhost:8080

### :x: Result
The console prints:
```
Exception in thread "DefaultHttpServer-ProcessingThread-17" java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for length 1
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
        at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4589)
        at java.base/java.lang.String.substring(String.java:2703)
        at cloud.piranha.http.impl.DefaultHttpServerRequest.parseHeader(DefaultHttpServerRequest.java:262)
        at cloud.piranha.http.impl.DefaultHttpServerRequest.parse(DefaultHttpServerRequest.java:241)
        at cloud.piranha.http.impl.DefaultHttpServerRequest.<init>(DefaultHttpServerRequest.java:95)
        at cloud.piranha.http.impl.DefaultHttpServerProcessingThread.run(DefaultHttpServerProcessingThread.java:85)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### My Environment
* Piranha Micro 22.6.0 *or* 21.11.0
* Google Chrome
* JRE from OpenJDK 18.0.1.1
* Windows

**Comment by Thihup** [comment] 2022-06-26 20:23
Hello @ParadoxV5, thanks for the bug report.
I couldn't reproduce it locally, but it seems to be related to the header parsing.
Could you please share which headers Google Chrome is sending in the request?

**Comment by ParadoxV5** [comment] 2022-06-26 20:37
> thanks for the bug report.

Whoa, didn’t expect a response this timely.

> Could you please share which headers Google Chrome is sending in the request?

(How do I record and copy the Chrome headers?)

Copy of the request fron DevTools as a fetch:
```js
fetch("https://localhost:8080/", {
  "headers": {
    "sec-ch-ua": "\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"104\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "upgrade-insecure-requests": "1"
  },
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET",
  "mode": "cors",
  "credentials": "omit"
});
```

**Comment by ParadoxV5** [comment] 2022-06-26 20:39
<details><summary>Additional experimentation using Piranha Micro 22.6.0</summary>

* `java.lang.StringIndexOutOfBoundsException` occurs with `--https-port 8080`
* With `--https-port` set to something else:
```
javax.net.ssl.SSLHandshakeException: No available authentication scheme
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:358)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:305)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateProducer.onProduceCertificate(CertificateMessage.java:972)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateProducer.produce(CertificateMessage.java:961)
        at java.base/sun.security.ssl.SSLHandshake.produce(SSLHandshake.java:440)
        at java.base/sun.security.ssl.ClientHello$T13ClientHelloConsumer.goServerHello(ClientHello.java:1246)
        at java.base/sun.security.ssl.ClientHello$T13ClientHelloConsumer.consume(ClientHello.java:1182)
        at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.onClientHello(ClientHello.java:840)
        at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.consume(ClientHello.java:801)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
        at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:915)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1006)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:966)
        at cloud.piranha.http.impl.DefaultHttpServerRequest.parse(DefaultHttpServerRequest.java:227)
        at cloud.piranha.http.impl.DefaultHttpServerRequest.<init>(DefaultHttpServerRequest.java:95)
        at cloud.piranha.http.impl.DefaultHttpServerProcessingThread.run(DefaultHttpServerProcessingThread.java:85)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
* With `--http-port` set and `--https-port` unset: **[EDIT: and connecting via `http://`]**
```
javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
        at java.base/sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:451)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:175)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
        at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:915)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1006)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:966)
        at cloud.piranha.http.impl.DefaultHttpServerRequest.parse(DefaultHttpServerRequest.java:227)
        at cloud.piranha.http.impl.DefaultHttpServerRequest.<init>(DefaultHttpServerRequest.java:95)
        at cloud.piranha.http.impl.DefaultHttpServerProcessingThread.run(DefaultHttpServerProcessingThread.java:85)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
* With both `--http-port` and `--https-port` set:
  * HTTP does nothing (could be my end)
  * HTTPS is again `javax.net.ssl.SSLHandshakeException` (could be because my localhost doesn’t have HTTPS)
</details>

**Comment by mnriem** [comment] 2022-06-26 22:31
Can you please try it with Java 17?

**Comment by Thihup** [comment] 2022-06-27 10:50
> (How do I record and copy the Chrome headers?)

Can you please share the request as cURL - Bash?

The root page right now doesn't return any content - 404, so maybe you should a web application.

**Comment by Thihup** [comment] 2022-06-27 10:54
I think I could reproduce it. Trying to access the 8080 port with "https" protocol doesn't work right. You should specify other port than the default (8080)

**Comment by ParadoxV5** [comment] 2022-06-28 20:58
> Can you please share the request as cURL - Bash?
> @Thihup

```
curl 'https://localhost:8080/' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="104", " Not A;Brand";v="99", "Google Chrome";v="104"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  --compressed
```

**Comment by ParadoxV5** [comment] 2022-06-28 21:16
> You should specify other port than the default (8080)

For that, the default ports aren’t even (accessibly) documented. It’s only just now that I searched the sources and identified [Lines 86–94 in `/micro/dist/src/…/MicroPiranha.java`](../blob/88d45ba7cb29bf4b53c821fb8bff9ef1a92414ee/micro/dist/src/main/java/cloud/piranha/micro/MicroPiranha.java#L86-L94)

With that identified, `StringIndexOutOfBoundsException` is likely due to the browser accessing the HTTP port with HTTPS protocol.
*updates issue*

**Comment by mnriem** [comment] 2022-07-03 14:37
Can we close this one out now?

**Comment by ParadoxV5** [comment] 2022-07-03 18:12
> Can we close this one out now?

If we ignore this exception because it’s caused by end-users’ inappropriate usage, I suppose.

**Comment by mnriem** [comment] 2022-07-03 21:34
@Thihup Thoughts on this one?

**Comment by Thihup** [comment] 2022-07-04 12:16
I think we can close this one and open a new issue for detecting HTTPS request in HTTP endpoint and provide a better error message than a StringIndexOutOfBoundsException

**Comment by mnriem** [comment] 2022-07-04 12:24
@Thihup Please go ahead!

**Comment by mnriem** [comment] 2022-07-04 12:43
Closing this out as the underlying issue has been identified and an enhancement issue (#2629) has been filed.

**Closed as completed by mnriem** 2022-07-04 12:43 UTC
Labels: bug
