### ISSUE TITLE
Add JPMS support

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#724] opened 2020-05-13 11:29 UTC
Is there any plan to add JPMS to the server?

**Comment by arjantijms** [comment] 2020-05-13 12:00
As soon as we switched fully over to JDK 11+ we should surely look at that!

**Comment by hrstoyanov** [comment] 2020-05-15 17:02
Being JPMS-based will be a big differentiate for me!

**Comment by manorrock** [comment] 2020-08-11 22:02
Closing this as a duplicate of #1022

**Closed by manorrock** 2020-08-11 22:02 UTC
