### ISSUE TITLE
Merge ext-tck-servlet-all-http-impls and ext-tck-servlet workflows

### ISSUE THREAD

**Issue by manorrock** [piranhacloud/piranha#1360] opened 2020-12-24 18:05 UTC
Make it possible to trigger a specific HTTP implementation using the manual workflow functionality. Introduce a default that runs on a schedule.

**Comment by Thihup** [comment] 2021-02-27 19:24
Closing this as a duplicate of #1524

**Closed by Thihup** 2021-02-27 19:24 UTC
